"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os  # أضف هذا في الأعلى مع بقية الاستيرادات
from pathlib import Path

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_URL = '/media/'

# ... بقية الإعدادات الموجودة ...

# تأكد من وجود هذا التعريف
BASE_DIR = Path(__file__).resolve().parent.parent

# ثم عرف ARCHIVE_ROOT
ARCHIVE_ROOT = os.path.join(BASE_DIR, 'system_archive')
if not os.path.exists(ARCHIVE_ROOT):
    os.makedirs(ARCHIVE_ROOT)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&j60yb1i-h-b_89)*xf^gm!9&^)%pa^v2#_zs284_4wgthzh&w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'corsheaders',

    'AppMain.apps.AppMainConfig',
    'AppOfDocuments',
    'AppSettings.apps.AppsettingsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'AppSettings.context_processors.system_settings_context',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

#DATABASES = {
#    'default': {
 #       'ENGINE': 'django.db.backends.sqlite3',
 #       'NAME': BASE_DIR / 'db.sqlite3',
 #   }
#}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db.archive',
        'USER': 'postgres',
        'PASSWORD': '123',
        'HOST': 'localhost',  # أو IP السيرفر
        'PORT': '5432',       # المنفذ الافتراضي لـ PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
#STATICFILES_DIRS = [BASE_DIR / 'AppMain/static']
#STATICFILES_DIRS = [BASE_DIR / 'AppOfDocuments/static']


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




MEDIA_URL = '/mediaa/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediaa')



# مسار الأرشيف الرئيسي
ARCHIVE_ROOT = os.path.join(BASE_DIR, 'system_archive')

# إعدادات CORS (للتطوير فقط)
CORS_ALLOW_ALL_ORIGINS = True  # أو تحديد origins معينة



# # مدة انتهاء الجلسة بعد الخمول (بالثواني)
# SESSION_COOKIE_AGE = 60  # 15 دقيقة = 900 ثانية

# # يتم تجديد الجلسة عند كل طلب؟ (False تعني الخمول يسبب الانتهاء)
# SESSION_SAVE_EVERY_REQUEST = False

# # نوع التخزين للجلسة
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # تنتهي عند إغلاق المتصفح
BASE_DIR = Path(__file__).resolve().parent.parent
