# Generated by Django 3.2.25 on 2025-05-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('document_title', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('export_date', models.DateField()),
                ('notes', models.TextField()),
                ('export_image', models.BinaryField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('document_title', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('import_date', models.DateField()),
                ('notes', models.TextField()),
                ('import_image', models.BinaryField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
