# Generated by Django 3.2.25 on 2025-06-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Export',
        ),
        migrations.DeleteModel(
            name='Import',
        ),
    ]
