# Generated by Django 3.2.25 on 2025-06-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.TextField()),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('export_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('export_image', models.BinaryField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('import_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('import_image', models.BinaryField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'imports',
                'managed': False,
            },
        ),
    ]
