# Generated by Django 3.2.25 on 2025-06-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOfDocuments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationProjects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('students_count', models.IntegerField()),
                ('project_name', models.CharField(max_length=255)),
                ('group_names', models.TextField(blank=True, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'graduation_projects',
                'managed': False,
            },
        ),
    ]
