# Generated by Django 3.2.25 on 2025-06-13 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOfDocuments', '0002_graduationprojects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduationprojects',
            options={'managed': True},
        ),
    ]
