# Generated by Django 3.2.25 on 2025-06-13 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOfDocuments', '0003_alter_graduationprojects_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationprojects',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AppOfDocuments.employee'),
        ),
    ]
