# Generated by Django 3.2.25 on 2025-06-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOfDocuments', '0006_remove_graduationprojects_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='clipboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_date', models.DateField()),
                ('safe_image', models.BinaryField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clipboard',
                'managed': False,
            },
        ),
    ]
