# Generated by Django 3.2.25 on 2025-06-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOfDocuments', '0007_clipboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clipboard',
            options={},
        ),
    ]
