# Generated by Django 3.2.25 on 2025-06-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOfDocuments', '0008_alter_clipboard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clipboard',
            options={'managed': False, 'verbose_name': 'حافظة', 'verbose_name_plural': 'الحافظات'},
        ),
    ]
