# Generated by Django 3.2.25 on 2025-06-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppOfDocuments', '0009_alter_clipboard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='export',
            options={'managed': True},
        ),
    ]
