# Generated by Django 3.2.25 on 2025-06-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOfDocuments', '0010_alter_export_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='export',
            name='employee',
            field=models.ForeignKey(db_column='employee_id', default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='AppOfDocuments.employee'),
            preserve_default=False,
        ),
    ]
