# Generated by Django 3.2.25 on 2025-06-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOfDocuments', '0011_auto_20250616_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='export',
            name='employee',
            field=models.ForeignKey(db_column='full_name', on_delete=django.db.models.deletion.DO_NOTHING, to='AppOfDocuments.employee'),
        ),
    ]
