# Generated by Django 3.2.25 on 2025-06-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOfDocuments', '0013_alter_export_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('word_file', models.BinaryField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ready_templates',
                'managed': False,
            },
        ),
    ]
