# Generated by Django 3.2.25 on 2025-06-20 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppOfDocuments', '0014_readytemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stamp_type', models.CharField(max_length=100)),
                ('stamp_image', models.BinaryField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.DO_NOTHING, to='AppOfDocuments.employee')),
            ],
            options={
                'db_table': 'stamps',
                'managed': True,
            },
        ),
    ]
