# Generated by Django 5.1.4 on 2025-05-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(default='ar', max_length=10)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
