# Generated by Django 3.2.25 on 2025-06-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/AppSettings/logos/'),
        ),
    ]
