# Generated by Django 3.2.25 on 2025-06-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSettings', '0002_alter_systemsettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار النظام'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='system_name',
            field=models.CharField(default='نظام الأرشيف', max_length=255, verbose_name='اسم النظام'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='timezone',
            field=models.CharField(default='Asia/Riyadh', max_length=100),
        ),
    ]
