# Generated by Django 3.2.25 on 2025-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSettings', '0003_auto_20250615_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(choices=[('daily', 'كل يوم'), ('weekly', 'كل أسبوع'), ('monthly', 'كل شهر')], default='daily', max_length=10)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'تمت بنجاح'), ('pending', 'قيد التنفيذ'), ('failed', 'فشلت العملية')], default='pending', max_length=20)),
            ],
        ),
    ]
